%%% The following module is generated by the get-test-params.sh script.
%%% Do not edit by hand.

-module(isomorphism_SUITE).
-include_lib("common_test/include/ct.hrl").
-export([all/0]).

%% The test suite is generated from the test manifest file ct/isomorphism_SUITE_data/manifest.ttl

-export([jena_iso_00/1, jena_iso_01/1, jena_iso_02/1, jena_iso_03/1, jena_iso_04/1, jena_iso_05/1, jena_iso_06/1, jena_iso_07/1, jena_iso_20/1, jena_iso_21/1, jena_iso_22/1, jena_iso_23/1, jena_iso_24/1, jena_iso_62/1, jena_iso_63/1, jena_iso_64/1, jena_iso_65/1, jena_iso_66/1]).
-export([init_per_suite/1, end_per_suite/1]).
-export([init_per_testcase/2, end_per_testcase/2]).

init_per_suite(Config) ->
    {ok, _} = application:ensure_all_started(lagra),
    Config.

end_per_suite(_Config) ->
    application:stop(lagra),
    ok.

init_per_testcase(_, Config) ->
    Store1 = lagra:create_store(trivial),
    Store2 = lagra:create_store(trivial),
    [{store1, Store1}, {store2, Store2}|Config].

end_per_testcase(_, Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    lagra:destroy_store(Store1),
	lagra:destroy_store(Store2).


jena_iso_00(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_00-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_00-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    true = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_01(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_01-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_01-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    true = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_02(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_02-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_02-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    false = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_03(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_03-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_03-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    false = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_04(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_04-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_04-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    false = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_05(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_05-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_05-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    true = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_06(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_06-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_06-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    true = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_07(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_07-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_07-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    false = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_20(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_20-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_20-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    true = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_21(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_21-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_21-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    false = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_22(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_22-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_22-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    true = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_23(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_23-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_23-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    false = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_24(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_24-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_24-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    false = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_62(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_62-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_62-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    false = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_63(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_63-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_63-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    true = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_64(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_64-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_64-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    true = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_65(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_65-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_65-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    true = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).

jena_iso_66(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_66-b.nt"),
                      [read]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_66-a.nt"),
                      [read]),
    ok = lagra:parse(Store1, File1, ntriples, [allow_relative]),
    ok = lagra:parse(Store2, File2, ntriples, [allow_relative]),
    true = lagra:isomorphic(Store1, {iri, "urn:nil"}, Store2, {iri, "urn:nil"}).


all() ->
    [jena_iso_00, jena_iso_01, jena_iso_02, jena_iso_03, jena_iso_04, jena_iso_05, jena_iso_06, jena_iso_07, jena_iso_20, jena_iso_21, jena_iso_22, jena_iso_23, jena_iso_24, jena_iso_62, jena_iso_63, jena_iso_64, jena_iso_65, jena_iso_66].

