%%% The following module is generated by the gen-parser-test-suite.sh script.
%%% Do not edit by hand.

-module(isomorphism_SUITE).
-include_lib("common_test/include/ct.hrl").
-export([all/0]).

%% The test suite is generated from the test manifest file ct/isomorphism_SUITE_data/manifest.ttl

-export(['jena-iso_00'/1]).
-export(['jena-iso_01'/1]).
-export(['jena-iso_02'/1]).
-export(['jena-iso_03'/1]).
-export(['jena-iso_04'/1]).
-export(['jena-iso_05'/1]).
-export(['jena-iso_06'/1]).
-export(['jena-iso_07'/1]).
-export(['jena-iso_20'/1]).
-export(['jena-iso_21'/1]).
-export(['jena-iso_22'/1]).
-export(['jena-iso_23'/1]).
-export(['jena-iso_24'/1]).
-export(['jena-iso_62'/1]).
-export(['jena-iso_63'/1]).
-export(['jena-iso_65'/1]).
-export(['jena-iso_66'/1]).
-export(['easyrdf-bad-01'/1]).
-export(['easyrdf-bad-02'/1]).
-export(['easyrdf-bad-03'/1]).
-export(['easyrdf-bad-04'/1]).
-export(['easyrdf-bad-05'/1]).
-export(['easyrdf-good-01'/1]).
-export(['easyrdf-good-02'/1]).
-export(['easyrdf-good-03'/1]).
-export(['easyrdf-good-04'/1]).
-export(['easyrdf-good-05'/1]).
-export(['easyrdf-good-06'/1]).
-export(['easyrdf-good-07'/1]).
-export(['node-rdf-01'/1]).
-export(['node-rdf-02'/1]).
-export([init_per_suite/1, end_per_suite/1]).
-export([init_per_testcase/2, end_per_testcase/2]).

init_per_suite(Config) ->
    {ok, _} = application:ensure_all_started(lagra),
    [{prefix, ""}|Config].

end_per_suite(_Config) ->
    application:stop(lagra),
    ok.

init_per_testcase(_, Config) ->
    Store1 = lagra:create_store(trivial),
    Store2 = lagra:create_store(trivial),
    [{store1, Store1}, {store2, Store2}|Config].

end_per_testcase(_, Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    lagra:destroy_store(Store1),
	lagra:destroy_store(Store2).


'jena-iso_00'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_00-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_00-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_01'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_01-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_01-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_02'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_02-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_02-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    false = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_03'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_03-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_03-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    false = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_04'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_04-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_04-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    false = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_05'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_05-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_05-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_06'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_06-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_06-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_07'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_07-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_07-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    false = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_20'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_20-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_20-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_21'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_21-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_21-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    false = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_22'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_22-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_22-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_23'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_23-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_23-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    false = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_24'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_24-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_24-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    false = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_62'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_62-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_62-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    false = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_63'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_63-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_63-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_65'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_65-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_65-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'jena-iso_66'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_66-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "jena-iso_66-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'easyrdf-bad-01'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-bad-01-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-bad-01-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    false = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'easyrdf-bad-02'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-bad-02-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-bad-02-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    false = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'easyrdf-bad-03'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-bad-03-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-bad-03-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    false = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'easyrdf-bad-04'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-bad-04-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-bad-04-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    false = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'easyrdf-bad-05'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-bad-05-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-bad-05-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    false = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'easyrdf-good-01'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-good-01-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-good-01-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'easyrdf-good-02'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-good-02-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-good-02-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'easyrdf-good-03'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-good-03-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-good-03-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'easyrdf-good-04'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-good-04-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-good-04-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'easyrdf-good-05'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-good-05-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-good-05-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'easyrdf-good-06'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-good-06-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-good-06-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'easyrdf-good-07'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-good-07-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "easyrdf-good-07-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'node-rdf-01'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "node-rdf-01-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "node-rdf-01-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    true = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).

'node-rdf-02'(Config) ->
    Store1 = ?config(store1, Config),
    Store2 = ?config(store2, Config),
    {ok, File1} = file:open(
        filename:join(?config(data_dir, Config),
                              "node-rdf-02-b.nt"),
                      [read, {encoding, utf8}, binary]),
    {ok, File2} = file:open(
        filename:join(?config(data_dir, Config),
                              "node-rdf-02-a.nt"),
                      [read, {encoding, utf8}, binary]),
    ok = lagra:parse(Store1, File1, ntriples, #{allow_relative=>true}),
    ok = lagra:parse(Store2, File2, ntriples, #{allow_relative=>true}),
    false = lagra:isomorphic(Store1, {iri, <<"urn:nil">>}, Store2, {iri, <<"urn:nil">>}).


all() ->
    ['jena-iso_00','jena-iso_01','jena-iso_02','jena-iso_03','jena-iso_04','jena-iso_05','jena-iso_06','jena-iso_07','jena-iso_20','jena-iso_21','jena-iso_22','jena-iso_23','jena-iso_24','jena-iso_62','jena-iso_63','jena-iso_65','jena-iso_66','easyrdf-bad-01','easyrdf-bad-02','easyrdf-bad-03','easyrdf-bad-04','easyrdf-bad-05','easyrdf-good-01','easyrdf-good-02','easyrdf-good-03','easyrdf-good-04','easyrdf-good-05','easyrdf-good-06','easyrdf-good-07','node-rdf-01','node-rdf-02'].
